export const IDS = Object.freeze({
  dimension: "pinene_pvp:pvp_island",
  dragonRelic: "pinene_pvp:dragon_relic",
  dragonRelicBlock: "pinene_pvp:dragon_relic_block",
  dragonRelicDisplay: "pinene_pvp:dragon_relic_display",
  dragonRelicDropped: "pinene_pvp:dragon_relic_dropped",
  markerBlock: "pinene_pvp:temporary_base_marker_block",
  islandCore: "pinene_pvp:island_core",
  protectedFoundation: "pinene_pvp:protected_foundation",
  protectedStructure: "pinene_pvp:protected_structure",
  protectedGlass: "pinene_pvp:protected_glass",
  protectedLight: "pinene_pvp:protected_light",
  protectedStone: "pinene_pvp:protected_stone",
  protectedMetal: "pinene_pvp:protected_metal",
  protectedObsidian: "pinene_pvp:protected_obsidian",
  protectedWhite: "pinene_pvp:protected_white",
  protectedBricks: "pinene_pvp:protected_bricks",
  protectedGlowGlass: "pinene_pvp:protected_glow_glass",
  protectedWood: "pinene_pvp:protected_wood",
  protectedDark: "pinene_pvp:protected_dark",
  protectedCopper: "pinene_pvp:protected_copper",
  protectedGold: "pinene_pvp:protected_gold",
  protectedRed: "pinene_pvp:protected_red",
  protectedBlue: "pinene_pvp:protected_blue",
  protectedGreen: "pinene_pvp:protected_green",
  protectedYellow: "pinene_pvp:protected_yellow",
  protectedOrange: "pinene_pvp:protected_orange",
  protectedPurple: "pinene_pvp:protected_purple",
  protectedCyan: "pinene_pvp:protected_cyan",
  protectedPink: "pinene_pvp:protected_pink",
  protectedBlack: "pinene_pvp:protected_black",
  protectedGray: "pinene_pvp:protected_gray",
  protectedSandstone: "pinene_pvp:protected_sandstone",
  protectedPrismarine: "pinene_pvp:protected_prismarine",
  protectedNetherBricks: "pinene_pvp:protected_nether_bricks",
  protectedMossyStone: "pinene_pvp:protected_mossy_stone",
  protectedEmerald: "pinene_pvp:protected_emerald",
  protectedAmethyst: "pinene_pvp:protected_amethyst",
  protectedCobblestone: "pinene_pvp:protected_cobblestone",
  protectedSmoothStone: "pinene_pvp:protected_smooth_stone",
  protectedAndesite: "pinene_pvp:protected_andesite",
  protectedPolishedAndesite: "pinene_pvp:protected_polished_andesite",
  protectedDiorite: "pinene_pvp:protected_diorite",
  protectedPolishedDiorite: "pinene_pvp:protected_polished_diorite",
  protectedGranite: "pinene_pvp:protected_granite",
  protectedPolishedGranite: "pinene_pvp:protected_polished_granite",
  protectedDeepslate: "pinene_pvp:protected_deepslate",
  protectedCobbledDeepslate: "pinene_pvp:protected_cobbled_deepslate",
  protectedPolishedDeepslate: "pinene_pvp:protected_polished_deepslate",
  protectedDeepslateBricks: "pinene_pvp:protected_deepslate_bricks",
  protectedDeepslateTiles: "pinene_pvp:protected_deepslate_tiles",
  protectedTuff: "pinene_pvp:protected_tuff",
  protectedPolishedTuff: "pinene_pvp:protected_polished_tuff",
  protectedTuffBricks: "pinene_pvp:protected_tuff_bricks",
  protectedCalcite: "pinene_pvp:protected_calcite",
  protectedBasalt: "pinene_pvp:protected_basalt",
  protectedPolishedBasalt: "pinene_pvp:protected_polished_basalt",
  protectedBlackstone: "pinene_pvp:protected_blackstone",
  protectedPolishedBlackstone: "pinene_pvp:protected_polished_blackstone",
  protectedEndStone: "pinene_pvp:protected_end_stone",
  protectedEndStoneBricks: "pinene_pvp:protected_end_stone_bricks",
  protectedPurpur: "pinene_pvp:protected_purpur",
});

export const STATE_KEYS = Object.freeze({
  relicState: "pinene_pvp:dragon_relic_state",
  markers: "pinene_pvp:temporary_base_markers",
  templateRevision: "pinene_pvp:island_template_revision",
  naturalIslandSearchIndex: "pinene_pvp:natural_island_search_index",
});

export const NATURAL_ISLAND_IMPORT = Object.freeze({
  searchSize: 64,
  importSize: 512,
  batchSize: 64,
  yMin: -64,
  yMax: 319,
  verticalTileSize: 64,
  sampleStep: 8,
  searchStart: 8192,
  searchSpacing: 192,
  defaultAttempts: 12,
  maxAttempts: 32,
  tickingAreaId: "pinene_pvp_island_source_scan",
  targetTickingAreaId: "pinene_pvp_island_target_copy",
  snapshotPrefix: "pinene_pvp:editor/natural_import/",
});

export const POC = Object.freeze({
  center: { x: 0, y: 64, z: 0 },
  platformRadius: 4,
  tickingAreaId: "pinene_pvp_poc_platform",
});

export const ISLAND_TEMPLATE = Object.freeze({
  prefix: "pinene_pvp:island/",
  revision: 1,
  maxTileHeight: 64,
});
