give @s pine:honey_bread 1
give @s pine:chocolate_bread 1
give @s pine:sweet_berry_bread 1
give @s pine:glow_berry_bread 1
give @s pine:apple_bread 1
give @s pine:pumpkin_bread 1
give @s pine:carrot_salad 1
give @s pine:kelp_salad 1
give @s pine:egg_toast 1
give @s pine:potato_sandwich 1
give @s pine:steak_sandwich 1
give @s pine:pork_sandwich 1
give @s pine:chicken_sandwich 1
give @s pine:mushroom_sandwich 1
give @s pine:honey_pork_sandwich 1
give @s pine:mushroom_cream_soup 1
give @s pine:pumpkin_soup 1
give @s pine:beef_stew 1
give @s pine:chicken_stew 1
give @s pine:seafood_soup 1
give @s pine:honey_chicken 1
give @s pine:chocolate_pancake 1
give @s pine:apple_pancake 1
give @s pine:glow_berry_pancake 1
give @s pine:pumpkin_pancake 1
give @s pine:carrot_cake 1
give @s pine:fruit_bowl 1
give @s pine:milk_bottle 1
give @s pine:butter 1
give @s pine:chocolate 1
