import { test,expect } from '@playwright/test';
import { fileURLToPath } from 'node:url';
test('published GA4 configuration respects consent on the real page',async({page})=>{
 let loads=0;
 await page.route('https://www.googletagmanager.com/**',route=>{loads++;return route.fulfill({status:200,body:''});});
 await page.route('https://*.google-analytics.com/**',route=>route.abort());
 await page.goto('/pine-server/?q=PRIVATE_QUERY#PRIVATE_FRAGMENT');
 await expect(page.locator('#pine-analytics')).toHaveAttribute('data-measurement-id','G-11K0Q4T42N');
 await expect(page.locator('#analytics-choice')).toBeVisible();
 expect(loads).toBe(0);
 await page.locator('[data-consent="yes"]').click();
 await expect.poll(()=>loads).toBe(1);
 const commands=await page.evaluate(()=>((window as any).dataLayer as IArguments[]).map(x=>Array.from(x)));
 const views=commands.filter(x=>x[0]==='event'&&x[1]==='page_view');
 expect(views).toHaveLength(1);
 expect(JSON.stringify(commands)).not.toMatch(/PRIVATE_QUERY|PRIVATE_FRAGMENT/);
 expect(commands.find(x=>x[0]==='config')?.[2]).toMatchObject({send_page_view:false});
 await page.locator('#analytics-settings').click();
 await page.locator('[data-consent="no"]').click();
 await page.reload();
 expect(loads).toBe(1);
 await expect(page.locator('#analytics-choice')).toBeHidden();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('GA4 waits for consent, strips queries and never sends search input',async({page})=>{
 let downloads=0;
 await page.route('https://www.googletagmanager.com/**',route=>{downloads++;return route.fulfill({status:200,body:''});});
 await page.route('https://*.google-analytics.com/**',route=>route.abort());
 await page.goto('/pine-server/database/items/?q=PRIVATE_TEXT');
 await page.evaluate(()=>localStorage.removeItem('pine-analytics-consent-v1'));
 await page.setContent('<div id="pine-analytics" data-measurement-id="G-TEST1234" data-content-group="mycology" data-entry-kind="recipe" data-entry-id="test-recipe"><section id="analytics-choice" hidden><button data-consent="yes">許可する</button><button data-consent="no">許可しない</button></section><button id="analytics-settings">設定</button></div><input id="guide-search">');
 await page.addScriptTag({path:fileURLToPath(new URL('../public/analytics.js',import.meta.url))});
 expect(downloads).toBe(0);
 await page.getByRole('button',{name:'許可しない',exact:true}).click();expect(downloads).toBe(0);
 await page.getByRole('button',{name:'設定',exact:true}).click();await page.getByRole('button',{name:'許可する',exact:true}).click();
 await expect.poll(()=>downloads).toBe(1);
 await page.locator('#guide-search').fill('DO_NOT_SEND_THIS');
 await expect.poll(()=>page.evaluate(()=>JSON.stringify((window as any).dataLayer))).toContain('pine_search');
 const data=await page.evaluate(()=>JSON.stringify((window as any).dataLayer));
 expect(data).not.toContain('PRIVATE_TEXT');expect(data).not.toContain('DO_NOT_SEND_THIS');expect(data).toContain('pine_recipe_view');
 await page.getByRole('button',{name:'設定',exact:true}).click();await page.getByRole('button',{name:'許可しない',exact:true}).click();
 const count=await page.evaluate(()=>(window as any).dataLayer.length);
 await page.locator('#guide-search').fill('another search');await page.waitForTimeout(1200);
 expect(await page.evaluate(()=>(window as any).dataLayer.length)).toBe(count);
});
