import { test, expect } from '@playwright/test';
import sections from '../src/data/dungeons-guide.json' with { type: 'json' };
import records from '../src/data/field-guide.json' with { type: 'json' };
const categoryCount=(id:string)=>sections.find(section=>section.id===id)!.entries.length;
test.beforeEach(async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('pine-analytics-consent-v1','no'));
 await page.route('https://static.cloudflareinsights.com/**',r=>r.fulfill({status:200,body:''}));
});
test('recipe search filters Dungeons by material and preserves the URL',async({page})=>{
 const recipes=records.filter(entry=>entry.contentId==='minecraft-dungeons'&&entry.kind==='recipe'&&entry.visibility==='public');
 await page.goto('/pine-server/database/recipes/?content=minecraft-dungeons');
 await expect(page.locator('[data-guide-entry]:visible')).toHaveCount(recipes.length);
 await page.getByLabel('名前・材料・説明を検索').fill('鉄インゴット');
 const matches=recipes.filter(entry=>[entry.name,entry.summary,entry.description,...entry.recipe!.ingredients.map(item=>item.name)].join(' ').includes('鉄インゴット'));
 await expect(page.locator('[data-guide-entry]:visible')).toHaveCount(matches.length);
 await page.reload();
 await expect(page.getByLabel('名前・材料・説明を検索')).toHaveValue('鉄インゴット');
 await expect(page.locator('[data-guide-entry]:visible')).toHaveCount(matches.length);
 await page.getByLabel('名前・材料・説明を検索').fill('該当なしテスト用');
 await expect(page.getByRole('heading',{name:'該当するレシピはありません'})).toBeVisible();
 await page.getByRole('button',{name:'条件をリセット'}).click();
 await expect(page.getByLabel('名前・材料・説明を検索')).toBeFocused();
 await expect(page.locator('[data-guide-entry]:visible')).toHaveCount(records.filter(entry=>entry.kind==='recipe'&&entry.visibility==='public').length);
});
test('melee recipes show materials, blueprint prerequisites and result links',async({page})=>{
 await page.goto('/pine-server/contents/minecraft-dungeons/');
 const section=page.locator('#dungeons-melee-recipes');
 await section.locator('summary').click();
 await expect(section.locator('[data-guide-entry]:visible')).toHaveCount(categoryCount('melee-recipes'));
 await section.locator('a[href$="/dungeons-sword-recipe/"]').click();
 await expect(page.getByText('鉄インゴット × 2',{exact:true})).toBeVisible();
 await expect(page.getByText('棒 × 1',{exact:true})).toBeVisible();
 await expect(page.getByText('完成数：1個',{exact:true})).toBeVisible();
 await page.goto('/pine-server/database/entries/dungeons-fighters-bindings-blueprint-recipe/');
 await expect(page.getByText('完成数：2個',{exact:true})).toBeVisible();
 await expect(page.locator('main')).toContainText('元になる装備が必要');
 await page.locator('a[href$="/dungeons-fighters-bindings/"]').first().click();
 await expect(page).toHaveURL(/dungeons-fighters-bindings\/$/);
});

test('Dungeons category navigation, expanded gear and recipe round trip', async ({ page }, info) => {
 const base = '/pine-server/';
 const errors: string[] = [];
 page.on('pageerror', error => errors.push(error.message));
 await page.goto(base + 'contents/minecraft-dungeons/');
 await expect(page.getByRole('heading', { level: 1 })).toHaveText('Minecraft Dungeons');
 await page.getByRole('link', { name: '装備・レシピを見る', exact: true }).click();
 await expect(page).toHaveURL(/#dungeons-guide-title$/);
 await page.getByRole('navigation', { name: 'Dungeonsの種類別一覧' }).getByRole('link', { name: '防具 196' }).click();
 const armor = page.locator('#dungeons-armor');
 await expect(armor.locator('[data-guide-entry]:visible')).toHaveCount(4);
 await armor.locator('summary').click();
 await expect(armor.locator('[data-guide-entry]:visible')).toHaveCount(196);
 await armor.locator('[data-guide-entry]').last().getByRole('link').click();
 await expect(page).toHaveURL(/database\/entries\/dungeons-verdant-leggings\/$/);
 await page.goBack();
 await page.getByRole('link', { name: '英雄の書を作る', exact: true }).click();
 await expect(page.getByText('金インゴット × 4', { exact: true })).toBeVisible();
 await page.getByRole('link', { name: '英雄の書の説明 →', exact: true }).click();
 await expect(page.getByRole('heading', { level: 1 })).toHaveText('英雄の書');
 await page.goto(base + 'database/entries/dungeons-harpoon-arrow-recipe/');
 await expect(page.getByText('完成数：6個', { exact: true })).toBeVisible();
 await expect(page.getByText('矢 × 4', { exact: true })).toBeVisible();
 await expect(page.getByText('鉄インゴット × 2', { exact: true })).toBeVisible();
 await expect(page.locator('.craft-grid')).toHaveCount(0);
 await page.getByRole('link', { name: /の説明 →$/ }).click();
 await expect(page).toHaveURL(/database\/entries\/dungeons-harpoon-arrow\/$/);
 await page.goto(base + 'database/entries/dungeons-soul-lantern-recipe/');
 await expect(page.locator('.craft-grid')).toBeVisible();
 await page.goto(base + 'contents/minecraft-dungeons/');
 await page.locator('.tech summary').click();
 await expect(page.locator('.tech')).toContainText('v2.0.6');
 await page.getByRole('navigation', { name: 'Dungeonsの種類別一覧' }).getByRole('link', { name: `弓・クロスボウのレシピ ${categoryCount('ranged-recipes')}` }).click();
 const rangedRecipes = page.locator('#dungeons-ranged-recipes');
 await rangedRecipes.locator('summary').click();
 await expect(rangedRecipes.locator('[data-guide-entry]:visible')).toHaveCount(categoryCount('ranged-recipes'));
 await rangedRecipes.locator('a[href$="/dungeons-harp-crossbow-blueprint-recipe/"]').click();
 await expect(page.getByText('完成数：2個', { exact: true })).toBeVisible();
 await expect(page.getByText('青色の設計図 × 1', { exact: true })).toBeVisible();
 await expect(page.getByText('ハープクロスボウ × 1', { exact: true })).toBeVisible();
 await expect(page.locator('.craft-grid td')).toHaveCount(2);
 await expect(page.locator('main')).toContainText('元になる装備が必要');
 await page.goto(base + 'database/entries/dungeons-soul-lantern-recipe/');
 await expect(page.getByText('魂のランタン（バニラ） × 1', { exact: true })).toBeVisible();
 await page.getByRole('link', { name: /の説明 →$/ }).click();
 await expect(page).toHaveURL(/database\/entries\/dungeons-soul-lantern\/$/);
 await expect(page.locator('main')).toContainText('13を消費');
 await expect(page.locator('main')).toContainText('ソウル不足時は召喚せず');
 await page.goto(base + 'contents/minecraft-dungeons/');
 await page.getByRole('navigation', { name: 'Dungeonsの種類別一覧' }).getByRole('link', { name: '防具の製作レシピ 88' }).click();
 const armorRecipes = page.locator('#dungeons-armor-recipes');
 await expect(armorRecipes.locator('[data-guide-entry]:visible')).toHaveCount(4);
 await armorRecipes.locator('summary').click();
 await expect(armorRecipes.locator('[data-guide-entry]:visible')).toHaveCount(88);
 await armorRecipes.locator('a[href$="/dungeons-beenest-chestplate-recipe/"]').click();
 await expect(page.getByText('ハニカム × 7', { exact: true })).toBeVisible();
 await expect(page.getByText('ミツバチの巣 × 1', { exact: true })).toBeVisible();
 await page.getByRole('link', { name: /の説明 →$/ }).click();
 await expect(page).toHaveURL(/database\/entries\/dungeons-beenest-chestplate\/$/);
 await page.locator('a[href$="/dungeons-beenest-chestplate-recipe/"]').click();
 await expect(page.locator('.craft-grid')).toBeVisible();
 await page.goto(base + 'contents/minecraft-dungeons/');
 await page.locator('img:visible').evaluateAll(images => Promise.all(images.map(image => {
  const img = image as HTMLImageElement; img.loading = 'eager'; return img.decode();
 })));
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
 await page.screenshot({ path: `artifacts/dungeons-${info.project.name}.png`, fullPage: true });
 expect(errors).toEqual([]);
});
