give @s pinene:r_mushroom_r01 1
give @s pinene:r_mushroom_r02 1
give @s pinene:r_mushroom_r03 1
give @s pinene:r_mushroom_r04 1
give @s pinene:r_mushroom_r05 1
give @s pinene:r_mushroom_r06 1
give @s pinene:r_mushroom_r07 1
give @s pinene:r_mushroom_r08 1
give @s pinene:r_mushroom_r09 1
give @s pinene:r_mushroom_r10 1
give @s pinene:r_mushroom_r11 1
give @s pinene:r_mushroom_r12 1
give @s pinene:r_mushroom_r13 1
give @s pinene:r_mushroom_r14 1
give @s pinene:r_mushroom_r15 1
give @s pinene:b_mushroom_b01 1
give @s pinene:b_mushroom_b02 1
give @s pinene:b_mushroom_b03 1
give @s pinene:b_mushroom_b04 1
give @s pinene:b_mushroom_b05 1
give @s pinene:b_mushroom_b06 1
give @s pinene:b_mushroom_b07 1
give @s pinene:b_mushroom_b08 1
give @s pinene:b_mushroom_b09 1
give @s pinene:b_mushroom_b10 1
give @s pinene:b_mushroom_b11 1
give @s pinene:b_mushroom_b12 1
give @s pinene:b_mushroom_b13 1
give @s pinene:b_mushroom_b14 1
give @s pinene:b_mushroom_b15 1
give @s pinene:b_mushroom_b16 1
give @s pinene:b_mushroom_b17 1
give @s pinene:b_mushroom_b18 1
give @s pinene:b_mushroom_b19 1
give @s pinene:b_mushroom_b20 1
