tag @s add dungeons:collected_dark_armour
tag @s add dungeons:collected_titans_shroud_armour
tag @s add dungeons:collected_grim_armour
tag @s add dungeons:collected_wither_armour
tag @s add dungeons:collected_wolf_armour
tag @s add dungeons:collected_black_wolf_armour
tag @s add dungeons:collected_fox_armour
tag @s add dungeons:collected_snow_armour
tag @s add dungeons:collected_frost_armour
tag @s add dungeons:collected_evocation_armour
tag @s add dungeons:collected_ember_armour
tag @s add dungeons:collected_verdant_armour
tag @s add dungeons:collected_ocelot_armour
tag @s add dungeons:collected_shadow_walker_armour
tag @s add dungeons:collected_spooky_gourdian_armour
tag @s add dungeons:collected_emerald_armour
tag @s add dungeons:collected_gilded_glory_armour
tag @s add dungeons:collected_opulent_armour
tag @s add dungeons:collected_turtle_armour
tag @s add dungeons:collected_nimble_turtle_armour
tag @s add dungeons:collected_squid_armour
tag @s add dungeons:collected_glow_squid_armour
tag @s add dungeons:collected_thief_armour
tag @s add dungeons:collected_spider_armour
tag @s add dungeons:collected_sprout_armour
tag @s add dungeons:collected_living_vines_armour
tag @s add dungeons:collected_piglin_armour
tag @s add dungeons:collected_golden_piglin_armour
tag @s add dungeons:collected_root_rot_armour
tag @s add dungeons:collected_black_spot_armour
tag @s add dungeons:collected_guard_armour
tag @s add dungeons:collected_ender_armour
tag @s add dungeons:collected_entertainer_armour
tag @s add dungeons:collected_troubadour_armour
tag @s add dungeons:collected_shulker_armour
tag @s add dungeons:collected_sturdy_shulker_armour
tag @s add dungeons:collected_teleportation_armour
tag @s add dungeons:collected_unstable_armour
tag @s add dungeons:collected_plate_armour
tag @s add dungeons:collected_full_metal_armour
tag @s add dungeons:collected_cauldron_armour
tag @s add dungeons:collected_ghostly_armour
tag @s add dungeons:collected_ghost_kindler_armour
tag @s add dungeons:collected_cloaked_skull_armour
tag @s add dungeons:collected_iron_hide_amulet
tag @s add dungeons:collected_soul_healer
tag @s add dungeons:collected_totem_of_regeneration
tag @s add dungeons:collected_shock_powder
tag @s add dungeons:collected_harvester
tag @s add dungeons:collected_gong_of_weakening
tag @s add dungeons:collected_death_cap_mushroom
tag @s add dungeons:collected_totem_of_casting
tag @s add dungeons:collected_enchanted_grass
tag @s add dungeons:collected_ice_wand
tag @s add dungeons:collected_satchel_of_elements
tag @s add dungeons:collected_wind_horn
tag @s add dungeons:collected_lightning_rod
tag @s add dungeons:collected_buzzy_nest
tag @s add dungeons:collected_boots_of_swiftness
tag @s add dungeons:collected_corrupted_seeds
tag @s add dungeons:collected_light_feather
tag @s add dungeons:collected_golem_kit
tag @s add dungeons:collected_totem_of_shielding
tag @s add dungeons:collected_blast_fungus
tag @s add dungeons:collected_powershaker
tag @s add dungeons:collected_spinblade
tag @s add dungeons:collected_scatter_mines
tag @s add dungeons:collected_updraft_tome
tag @s add dungeons:collected_enchanters_tome
tag @s add dungeons:collected_satchel_of_elixirs
tag @s add dungeons:collected_satchel_of_snacks
tag @s add dungeons:collected_eye_of_the_guardian
tag @s add dungeons:collected_corrupted_beacon
tag @s add dungeons:collected_soul_lantern
tag @s add dungeons:collected_ghost_cloak
tag @s add dungeons:collected_tome_of_duplication
tag @s add dungeons:collected_shadow_shifter
tag @s add dungeons:collected_vexing_chant
tag @s add dungeons:collected_corrupted_pumpkin
tag @s add dungeons:collected_hammer
tag @s add dungeons:collected_hammer_of_gravity
tag @s add dungeons:collected_stormlander
tag @s add dungeons:collected_katana
tag @s add dungeons:collected_dark_katana
tag @s add dungeons:collected_masters_katana
tag @s add dungeons:collected_soul_scythe
tag @s add dungeons:collected_jailors_scythe
tag @s add dungeons:collected_frost_scythe
tag @s add dungeons:collected_soul_knife
tag @s add dungeons:collected_eternal_knife
tag @s add dungeons:collected_truthseeker
tag @s add dungeons:collected_cleaving_axe
tag @s add dungeons:collected_firebrand
tag @s add dungeons:collected_highlands_axe
tag @s add dungeons:collected_claymore
tag @s add dungeons:collected_great_axeblade
tag @s add dungeons:collected_heartstealer
tag @s add dungeons:collected_broadsword
tag @s add dungeons:collected_rapier
tag @s add dungeons:collected_freezing_foil
tag @s add dungeons:collected_bee_stinger
tag @s add dungeons:collected_double_axe
tag @s add dungeons:collected_cursed_axe
tag @s add dungeons:collected_whirlwind
tag @s add dungeons:collected_daggers
tag @s add dungeons:collected_sheer_daggers
tag @s add dungeons:collected_frost_knives
tag @s add dungeons:collected_moon_daggers
tag @s add dungeons:collected_cutlass
tag @s add dungeons:collected_nameless_blade
tag @s add dungeons:collected_dancers_sword
tag @s add dungeons:collected_longsword
tag @s add dungeons:collected_diamond_longsword
tag @s add dungeons:collected_hawkbrand
tag @s add dungeons:collected_whip
tag @s add dungeons:collected_vine_whip
tag @s add dungeons:collected_sinister_sword
tag @s add dungeons:collected_skull_scythe
tag @s add dungeons:collected_bonehead_hammer
tag @s add dungeons:collected_battlestaff
tag @s add dungeons:collected_battlestaff_of_terror
tag @s add dungeons:collected_growing_staff
tag @s add dungeons:collected_tempest_knife
tag @s add dungeons:collected_chill_gale_knife
tag @s add dungeons:collected_resolute_tempest_knife
tag @s add dungeons:collected_anchor
tag @s add dungeons:collected_encrusted_anchor
tag @s add dungeons:collected_coral_blade
tag @s add dungeons:collected_sponge_striker
tag @s add dungeons:collected_mechanised_sawblade
tag @s add dungeons:collected_broken_sawblade
tag @s add dungeons:collected_bone_club
tag @s add dungeons:collected_bone_cudgel
tag @s add dungeons:collected_glaive
tag @s add dungeons:collected_grave_bane
tag @s add dungeons:collected_venom_glaive
tag @s add dungeons:collected_gauntlets
tag @s add dungeons:collected_fighters_bindings
tag @s add dungeons:collected_maulers
tag @s add dungeons:collected_soul_fists
tag @s add dungeons:collected_obsidian_claymore
tag @s add dungeons:collected_starless_night
tag @s add dungeons:collected_void_touched_blades
tag @s add dungeons:collected_the_beginning_and_the_end
tag @s add dungeons:collected_backstabber
tag @s add dungeons:collected_swift_striker
tag @s add dungeons:collected_cackling_broom
tag @s add dungeons:collected_bow
tag @s add dungeons:collected_bonebow
tag @s add dungeons:collected_twin_bow
tag @s add dungeons:collected_longbow
tag @s add dungeons:collected_guardian_bow
tag @s add dungeons:collected_red_snake
tag @s add dungeons:collected_snow_bow
tag @s add dungeons:collected_winters_touch
tag @s add dungeons:collected_wind_bow
tag @s add dungeons:collected_burst_gale_bow
tag @s add dungeons:collected_echo_of_the_valley
tag @s add dungeons:collected_twisting_vine_bow
tag @s add dungeons:collected_weeping_vine_bow
tag @s add dungeons:collected_void_bow
tag @s add dungeons:collected_call_of_the_void
tag @s add dungeons:collected_crossbow
tag @s add dungeons:collected_burst_crossbow
tag @s add dungeons:collected_corrupted_crossbow
tag @s add dungeons:collected_soul_hunter_crossbow
tag @s add dungeons:collected_exploding_crossbow
tag @s add dungeons:collected_imploding_crossbow
tag @s add dungeons:collected_firebolt_thrower
tag @s add dungeons:collected_soul_crossbow
tag @s add dungeons:collected_feral_soul_crossbow
tag @s add dungeons:collected_voidcaller
tag @s add dungeons:collected_harpoon_crossbow
tag @s add dungeons:collected_nautical_crossbow
tag @s add dungeons:collected_cog_crossbow
tag @s add dungeons:collected_pride_of_the_piglins
tag @s add dungeons:collected_heavy_crossbow
tag @s add dungeons:collected_doom_crossbow
tag @s add dungeons:collected_slayer_crossbow
tag @s add dungeons:collected_soul_bow
tag @s add dungeons:collected_nocturnal_bow
tag @s add dungeons:collected_bow_of_lost_souls
tag @s add dungeons:collected_void_bow
tag @s add dungeons:collected_call_of_the_void
tag @s add dungeons:collected_shadow_crossbow
tag @s add dungeons:collected_veiled_crossbow
tag @s add dungeons:collected_shrieking_crossbow
tag @s add dungeons:collected_haunted_bow
tag @s add dungeons:collected_webbed_bow