tag @a[hasitem={item=dungeons:dark_boots},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:dark_leggings},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:dark_chestplate},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:dark_helmet},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:titans_shroud_boots},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:titans_shroud_leggings},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:titans_shroud_chestplate},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:titans_shroud_helmet},tag=!dungeons:collected_dark_armour] add dungeons:collected_dark_armour
tag @a[hasitem={item=dungeons:titans_shroud_boots},tag=!dungeons:collected_titans_shroud_armour] add dungeons:collected_titans_shroud_armour
tag @a[hasitem={item=dungeons:titans_shroud_leggings},tag=!dungeons:collected_titans_shroud_armour] add dungeons:collected_titans_shroud_armour
tag @a[hasitem={item=dungeons:titans_shroud_chestplate},tag=!dungeons:collected_titans_shroud_armour] add dungeons:collected_titans_shroud_armour
tag @a[hasitem={item=dungeons:titans_shroud_helmet},tag=!dungeons:collected_titans_shroud_armour] add dungeons:collected_titans_shroud_armour
tag @a[hasitem={item=dungeons:grim_boots},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:grim_leggings},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:grim_chestplate},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:grim_helmet},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:wither_boots},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:wither_leggings},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:wither_chestplate},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:wither_helmet},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:wither_boots},tag=!dungeons:collected_wither_armour] add dungeons:collected_wither_armour
tag @a[hasitem={item=dungeons:wither_leggings},tag=!dungeons:collected_wither_armour] add dungeons:collected_wither_armour
tag @a[hasitem={item=dungeons:wither_chestplate},tag=!dungeons:collected_wither_armour] add dungeons:collected_wither_armour
tag @a[hasitem={item=dungeons:wither_helmet},tag=!dungeons:collected_wither_armour] add dungeons:collected_wither_armour
tag @a[hasitem={item=dungeons:wolf_boots},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:wolf_leggings},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:wolf_chestplate},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:wolf_helmet},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_boots},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_leggings},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_chestplate},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_helmet},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_boots},tag=!dungeons:collected_black_wolf_armour] add dungeons:collected_black_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_leggings},tag=!dungeons:collected_black_wolf_armour] add dungeons:collected_black_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_chestplate},tag=!dungeons:collected_black_wolf_armour] add dungeons:collected_black_wolf_armour
tag @a[hasitem={item=dungeons:black_wolf_helmet},tag=!dungeons:collected_black_wolf_armour] add dungeons:collected_black_wolf_armour
tag @a[hasitem={item=dungeons:fox_boots},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:fox_leggings},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:fox_chestplate},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:fox_helmet},tag=!dungeons:collected_wolf_armour] add dungeons:collected_wolf_armour
tag @a[hasitem={item=dungeons:fox_boots},tag=!dungeons:collected_fox_armour] add dungeons:collected_fox_armour
tag @a[hasitem={item=dungeons:fox_leggings},tag=!dungeons:collected_fox_armour] add dungeons:collected_fox_armour
tag @a[hasitem={item=dungeons:fox_chestplate},tag=!dungeons:collected_fox_armour] add dungeons:collected_fox_armour
tag @a[hasitem={item=dungeons:fox_helmet},tag=!dungeons:collected_fox_armour] add dungeons:collected_fox_armour
tag @a[hasitem={item=dungeons:snow_boots},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:snow_leggings},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:snow_chestplate},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:snow_helmet},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:frost_boots},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:frost_leggings},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:frost_chestplate},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:frost_helmet},tag=!dungeons:collected_snow_armour] add dungeons:collected_snow_armour
tag @a[hasitem={item=dungeons:frost_boots},tag=!dungeons:collected_frost_armour] add dungeons:collected_frost_armour
tag @a[hasitem={item=dungeons:frost_leggings},tag=!dungeons:collected_frost_armour] add dungeons:collected_frost_armour
tag @a[hasitem={item=dungeons:frost_chestplate},tag=!dungeons:collected_frost_armour] add dungeons:collected_frost_armour
tag @a[hasitem={item=dungeons:frost_helmet},tag=!dungeons:collected_frost_armour] add dungeons:collected_frost_armour
tag @a[hasitem={item=dungeons:ocelot_boots},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:ocelot_leggings},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:ocelot_chestplate},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:ocelot_helmet},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:shadow_walker_boots},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:shadow_walker_leggings},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:shadow_walker_chestplate},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:shadow_walker_helmet},tag=!dungeons:collected_ocelot_armour] add dungeons:collected_ocelot_armour
tag @a[hasitem={item=dungeons:shadow_walker_boots},tag=!dungeons:collected_shadow_walker_armour] add dungeons:collected_shadow_walker_armour
tag @a[hasitem={item=dungeons:shadow_walker_leggings},tag=!dungeons:collected_shadow_walker_armour] add dungeons:collected_shadow_walker_armour
tag @a[hasitem={item=dungeons:shadow_walker_chestplate},tag=!dungeons:collected_shadow_walker_armour] add dungeons:collected_shadow_walker_armour
tag @a[hasitem={item=dungeons:shadow_walker_helmet},tag=!dungeons:collected_shadow_walker_armour] add dungeons:collected_shadow_walker_armour
tag @a[hasitem={item=dungeons:evocation_boots},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:evocation_leggings},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:evocation_chestplate},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:evocation_helmet},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:ember_boots},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:ember_leggings},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:ember_chestplate},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:ember_helmet},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:ember_boots},tag=!dungeons:collected_ember_armour] add dungeons:collected_ember_armour
tag @a[hasitem={item=dungeons:ember_leggings},tag=!dungeons:collected_ember_armour] add dungeons:collected_ember_armour
tag @a[hasitem={item=dungeons:ember_chestplate},tag=!dungeons:collected_ember_armour] add dungeons:collected_ember_armour
tag @a[hasitem={item=dungeons:ember_helmet},tag=!dungeons:collected_ember_armour] add dungeons:collected_ember_armour
tag @a[hasitem={item=dungeons:verdant_boots},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:verdant_leggings},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:verdant_chestplate},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:verdant_helmet},tag=!dungeons:collected_evocation_armour] add dungeons:collected_evocation_armour
tag @a[hasitem={item=dungeons:verdant_boots},tag=!dungeons:collected_verdant_armour] add dungeons:collected_verdant_armour
tag @a[hasitem={item=dungeons:verdant_leggings},tag=!dungeons:collected_verdant_armour] add dungeons:collected_verdant_armour
tag @a[hasitem={item=dungeons:verdant_chestplate},tag=!dungeons:collected_verdant_armour] add dungeons:collected_verdant_armour
tag @a[hasitem={item=dungeons:verdant_helmet},tag=!dungeons:collected_verdant_armour] add dungeons:collected_verdant_armour
tag @a[hasitem={item=dungeons:spooky_gourdian_boots},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:spooky_gourdian_leggings},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:spooky_gourdian_chestplate},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:spooky_gourdian_helmet},tag=!dungeons:collected_grim_armour] add dungeons:collected_grim_armour
tag @a[hasitem={item=dungeons:spooky_gourdian_boots},tag=!dungeons:collected_spooky_gourdian] add dungeons:collected_spooky_gourdian
tag @a[hasitem={item=dungeons:spooky_gourdian_leggings},tag=!dungeons:collected_spooky_gourdian] add dungeons:collected_spooky_gourdian
tag @a[hasitem={item=dungeons:spooky_gourdian_chestplate},tag=!dungeons:collected_spooky_gourdian] add dungeons:collected_spooky_gourdian
tag @a[hasitem={item=dungeons:spooky_gourdian_helmet},tag=!dungeons:collected_spooky_gourdian] add dungeons:collected_spooky_gourdian
tag @a[hasitem={item=dungeons:emerald_boots},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:emerald_leggings},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:emerald_chestplate},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:emerald_helmet},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:opulent_boots},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:opulent_leggings},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:opulent_chestplate},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:opulent_helmet},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:opulent_boots},tag=!dungeons:collected_opulent_armour] add dungeons:collected_opulent_armour
tag @a[hasitem={item=dungeons:opulent_leggings},tag=!dungeons:collected_opulent_armour] add dungeons:collected_opulent_armour
tag @a[hasitem={item=dungeons:opulent_chestplate},tag=!dungeons:collected_opulent_armour] add dungeons:collected_opulent_armour
tag @a[hasitem={item=dungeons:opulent_helmet},tag=!dungeons:collected_opulent_armour] add dungeons:collected_opulent_armour
tag @a[hasitem={item=dungeons:gilded_glory_boots},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:gilded_glory_leggings},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:gilded_glory_chestplate},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:gilded_glory_helmet},tag=!dungeons:collected_emerald_armour] add dungeons:collected_emerald_armour
tag @a[hasitem={item=dungeons:gilded_glory_boots},tag=!dungeons:collected_gilded_glory_armour] add dungeons:collected_gilded_glory_armour
tag @a[hasitem={item=dungeons:gilded_glory_leggings},tag=!dungeons:collected_gilded_glory_armour] add dungeons:collected_gilded_glory_armour
tag @a[hasitem={item=dungeons:gilded_glory_chestplate},tag=!dungeons:collected_gilded_glory_armour] add dungeons:collected_gilded_glory_armour
tag @a[hasitem={item=dungeons:gilded_glory_helmet},tag=!dungeons:collected_gilded_glory_armour] add dungeons:collected_gilded_glory_armour
tag @a[hasitem={item=dungeons:turtle_boots},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:turtle_leggings},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:turtle_chestplate},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:turtle_helmet},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_boots},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_leggings},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_chestplate},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_helmet},tag=!dungeons:collected_turtle_armour] add dungeons:collected_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_boots},tag=!dungeons:collected_nimble_turtle_armour] add dungeons:collected_nimble_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_leggings},tag=!dungeons:collected_nimble_turtle_armour] add dungeons:collected_nimble_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_chestplate},tag=!dungeons:collected_nimble_turtle_armour] add dungeons:collected_nimble_turtle_armour
tag @a[hasitem={item=dungeons:nimble_turtle_helmet},tag=!dungeons:collected_nimble_turtle_armour] add dungeons:collected_nimble_turtle_armour
tag @a[hasitem={item=dungeons:squid_boots},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:squid_leggings},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:squid_chestplate},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:squid_helmet},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_boots},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_leggings},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_chestplate},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_helmet},tag=!dungeons:collected_squid_armour] add dungeons:collected_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_boots},tag=!dungeons:collected_glow_squid_armour] add dungeons:collected_glow_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_leggings},tag=!dungeons:collected_glow_squid_armour] add dungeons:collected_glow_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_chestplate},tag=!dungeons:collected_glow_squid_armour] add dungeons:collected_glow_squid_armour
tag @a[hasitem={item=dungeons:glow_squid_helmet},tag=!dungeons:collected_glow_squid_armour] add dungeons:collected_glow_squid_armour
tag @a[hasitem={item=dungeons:thief_boots},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:thief_leggings},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:thief_chestplate},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:thief_helmet},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:spider_boots},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:spider_leggings},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:spider_chestplate},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:spider_helmet},tag=!dungeons:collected_thief_armour] add dungeons:collected_thief_armour
tag @a[hasitem={item=dungeons:spider_boots},tag=!dungeons:collected_spider_armour] add dungeons:collected_spider_armour
tag @a[hasitem={item=dungeons:spider_leggings},tag=!dungeons:collected_spider_armour] add dungeons:collected_spider_armour
tag @a[hasitem={item=dungeons:spider_chestplate},tag=!dungeons:collected_spider_armour] add dungeons:collected_spider_armour
tag @a[hasitem={item=dungeons:spider_helmet},tag=!dungeons:collected_spider_armour] add dungeons:collected_spider_armour
tag @a[hasitem={item=dungeons:sprout_boots},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:sprout_leggings},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:sprout_chestplate},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:sprout_helmet},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:living_vines_boots},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:living_vines_leggings},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:living_vines_chestplate},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:living_vines_helmet},tag=!dungeons:collected_sprout_armour] add dungeons:collected_sprout_armour
tag @a[hasitem={item=dungeons:living_vines_boots},tag=!dungeons:collected_living_vines_armour] add dungeons:collected_living_vines_armour
tag @a[hasitem={item=dungeons:living_vines_leggings},tag=!dungeons:collected_living_vines_armour] add dungeons:collected_living_vines_armour
tag @a[hasitem={item=dungeons:living_vines_chestplate},tag=!dungeons:collected_living_vines_armour] add dungeons:collected_living_vines_armour
tag @a[hasitem={item=dungeons:living_vines_helmet},tag=!dungeons:collected_living_vines_armour] add dungeons:collected_living_vines_armour
tag @a[hasitem={item=dungeons:piglin_boots},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:piglin_leggings},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:piglin_chestplate},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:piglin_helmet},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_boots},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_leggings},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_chestplate},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_helmet},tag=!dungeons:collected_piglin_armour] add dungeons:collected_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_boots},tag=!dungeons:collected_golden_piglin_armour] add dungeons:collected_golden_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_leggings},tag=!dungeons:collected_golden_piglin_armour] add dungeons:collected_golden_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_chestplate},tag=!dungeons:collected_golden_piglin_armour] add dungeons:collected_golden_piglin_armour
tag @a[hasitem={item=dungeons:golden_piglin_helmet},tag=!dungeons:collected_golden_piglin_armour] add dungeons:collected_golden_piglin_armour
tag @a[hasitem={item=dungeons:root_rot_boots},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:root_rot_leggings},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:root_rot_chestplate},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:root_rot_helmet},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:black_spot_boots},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:black_spot_leggings},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:black_spot_chestplate},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:black_spot_helmet},tag=!dungeons:collected_root_rot_armour] add dungeons:collected_root_rot_armour
tag @a[hasitem={item=dungeons:black_spot_boots},tag=!dungeons:collected_black_spot_armour] add dungeons:collected_black_spot_armour
tag @a[hasitem={item=dungeons:black_spot_leggings},tag=!dungeons:collected_black_spot_armour] add dungeons:collected_black_spot_armour
tag @a[hasitem={item=dungeons:black_spot_chestplate},tag=!dungeons:collected_black_spot_armour] add dungeons:collected_black_spot_armour
tag @a[hasitem={item=dungeons:black_spot_helmet},tag=!dungeons:collected_black_spot_armour] add dungeons:collected_black_spot_armour
tag @a[hasitem={item=dungeons:guard_boots},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:guard_leggings},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:guard_chestplate},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:guard_helmet},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:ender_boots},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:ender_leggings},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:ender_chestplate},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:ender_helmet},tag=!dungeons:collected_guard_armour] add dungeons:collected_guard_armour
tag @a[hasitem={item=dungeons:ender_boots},tag=!dungeons:collected_ender_armour] add dungeons:collected_ender_armour
tag @a[hasitem={item=dungeons:ender_leggings},tag=!dungeons:collected_ender_armour] add dungeons:collected_ender_armour
tag @a[hasitem={item=dungeons:ender_chestplate},tag=!dungeons:collected_ender_armour] add dungeons:collected_ender_armour
tag @a[hasitem={item=dungeons:ender_helmet},tag=!dungeons:collected_ender_armour] add dungeons:collected_ender_armour
tag @a[hasitem={item=dungeons:entertainer_boots},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:entertainer_leggings},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:entertainer_chestplate},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:entertainer_helmet},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:troubadour_boots},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:troubadour_leggings},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:troubadour_chestplate},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:troubadour_helmet},tag=!dungeons:collected_entertainer_armour] add dungeons:collected_entertainer_armour
tag @a[hasitem={item=dungeons:troubadour_boots},tag=!dungeons:collected_troubadour_armour] add dungeons:collected_troubadour_armour
tag @a[hasitem={item=dungeons:troubadour_leggings},tag=!dungeons:collected_troubadour_armour] add dungeons:collected_troubadour_armour
tag @a[hasitem={item=dungeons:troubadour_chestplate},tag=!dungeons:collected_troubadour_armour] add dungeons:collected_troubadour_armour
tag @a[hasitem={item=dungeons:troubadour_helmet},tag=!dungeons:collected_troubadour_armour] add dungeons:collected_troubadour_armour
tag @a[hasitem={item=dungeons:shulker_boots},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:shulker_leggings},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:shulker_chestplate},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:shulker_helmet},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_boots},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_leggings},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_chestplate},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_helmet},tag=!dungeons:collected_shulker_armour] add dungeons:collected_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_boots},tag=!dungeons:collected_sturdy_shulker_armour] add dungeons:collected_sturdy_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_leggings},tag=!dungeons:collected_sturdy_shulker_armour] add dungeons:collected_sturdy_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_chestplate},tag=!dungeons:collected_sturdy_shulker_armour] add dungeons:collected_sturdy_shulker_armour
tag @a[hasitem={item=dungeons:sturdy_shulker_helmet},tag=!dungeons:collected_sturdy_shulker_armour] add dungeons:collected_sturdy_shulker_armour
tag @a[hasitem={item=dungeons:teleportation_boots},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:teleportation_leggings},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:teleportation_chestplate},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:teleportation_helmet},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:unstable_boots},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:unstable_leggings},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:unstable_chestplate},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:unstable_helmet},tag=!dungeons:collected_teleportation_armour] add dungeons:collected_teleportation_armour
tag @a[hasitem={item=dungeons:unstable_boots},tag=!dungeons:collected_unstable_armour] add dungeons:collected_unstable_armour
tag @a[hasitem={item=dungeons:unstable_leggings},tag=!dungeons:collected_unstable_armour] add dungeons:collected_unstable_armour
tag @a[hasitem={item=dungeons:unstable_chestplate},tag=!dungeons:collected_unstable_armour] add dungeons:collected_unstable_armour
tag @a[hasitem={item=dungeons:unstable_helmet},tag=!dungeons:collected_unstable_armour] add dungeons:collected_unstable_armour
tag @a[hasitem={item=dungeons:plate_boots},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:plate_leggings},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:plate_chestplate},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:plate_helmet},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:full_metal_boots},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:full_metal_leggings},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:full_metal_chestplate},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:full_metal_helmet},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:full_metal_boots},tag=!dungeons:collected_full_metal_armour] add dungeons:collected_full_metal_armour
tag @a[hasitem={item=dungeons:full_metal_leggings},tag=!dungeons:collected_full_metal_armour] add dungeons:collected_full_metal_armour
tag @a[hasitem={item=dungeons:full_metal_chestplate},tag=!dungeons:collected_full_metal_armour] add dungeons:collected_full_metal_armour
tag @a[hasitem={item=dungeons:full_metal_helmet},tag=!dungeons:collected_full_metal_armour] add dungeons:collected_full_metal_armour
tag @a[hasitem={item=dungeons:ghostly_boots},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghostly_leggings},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghostly_chestplate},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghostly_helmet},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghost_kindler_boots},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghost_kindler_leggings},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghost_kindler_chestplate},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghost_kindler_helmet},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:ghost_kindler_boots},tag=!dungeons:collected_ghost_kindler_armour] add dungeons:collected_ghost_kindler_armour
tag @a[hasitem={item=dungeons:ghost_kindler_leggings},tag=!dungeons:collected_ghost_kindler_armour] add dungeons:collected_ghost_kindler_armour
tag @a[hasitem={item=dungeons:ghost_kindler_chestplate},tag=!dungeons:collected_ghost_kindler_armour] add dungeons:collected_ghost_kindler_armour
tag @a[hasitem={item=dungeons:ghost_kindler_helmet},tag=!dungeons:collected_ghost_kindler_armour] add dungeons:collected_ghost_kindler_armour
tag @a[hasitem={item=dungeons:cauldron_boots},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:cauldron_leggings},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:cauldron_chestplate},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:cauldron_helmet},tag=!dungeons:collected_plate_armour] add dungeons:collected_plate_armour
tag @a[hasitem={item=dungeons:cauldron_boots},tag=!dungeons:collected_cauldron_armour] add dungeons:collected_cauldron_armour
tag @a[hasitem={item=dungeons:cauldron_leggings},tag=!dungeons:collected_cauldron_armour] add dungeons:collected_cauldron_armour
tag @a[hasitem={item=dungeons:cauldron_chestplate},tag=!dungeons:collected_cauldron_armour] add dungeons:collected_cauldron_armour
tag @a[hasitem={item=dungeons:cauldron_helmet},tag=!dungeons:collected_cauldron_armour] add dungeons:collected_cauldron_armour
tag @a[hasitem={item=dungeons:cloaked_skull_boots},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:cloaked_skull_leggings},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:cloaked_skull_chestplate},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:cloaked_skull_helmet},tag=!dungeons:collected_ghostly_armour] add dungeons:collected_ghostly_armour
tag @a[hasitem={item=dungeons:cloaked_skull_boots},tag=!dungeons:collected_cloaked_skull_armour] add dungeons:collected_cloaked_skull_armour
tag @a[hasitem={item=dungeons:cloaked_skull_leggings},tag=!dungeons:collected_cloaked_skull_armour] add dungeons:collected_cloaked_skull_armour
tag @a[hasitem={item=dungeons:cloaked_skull_chestplate},tag=!dungeons:collected_cloaked_skull_armour] add dungeons:collected_cloaked_skull_armour
tag @a[hasitem={item=dungeons:cloaked_skull_helmet},tag=!dungeons:collected_cloaked_skull_armour] add dungeons:collected_cloaked_skull_armour