tag @a[hasitem={item=minecraft:bow},tag=!dungeons:collected_bow] add dungeons:collected_bow
tag @a[hasitem={item=dungeons:bonebow},tag=!dungeons:collected_bow] add dungeons:collected_bow
tag @a[hasitem={item=dungeons:twin_bow},tag=!dungeons:collected_bow] add dungeons:collected_bow
tag @a[hasitem={item=dungeons:bonebow},tag=!dungeons:collected_bonebow] add dungeons:collected_bonebow
tag @a[hasitem={item=dungeons:twin_bow},tag=!dungeons:collected_twin_bow] add dungeons:collected_twin_bow
tag @a[hasitem={item=dungeons:longbow},tag=!dungeons:collected_longbow] add dungeons:collected_longbow
tag @a[hasitem={item=dungeons:guardian_bow},tag=!dungeons:collected_longbow] add dungeons:collected_longbow
tag @a[hasitem={item=dungeons:red_snake},tag=!dungeons:collected_longbow] add dungeons:collected_longbow
tag @a[hasitem={item=dungeons:guardian_bow},tag=!dungeons:collected_guardian_bow] add dungeons:collected_guardian_bow
tag @a[hasitem={item=dungeons:red_snake},tag=!dungeons:collected_red_snake] add dungeons:collected_red_snake
tag @a[hasitem={item=dungeons:snow_bow},tag=!dungeons:collected_snow_bow] add dungeons:collected_snow_bow
tag @a[hasitem={item=dungeons:winters_touch},tag=!dungeons:collected_snow_touch] add dungeons:collected_snow_bow
tag @a[hasitem={item=dungeons:winters_touch},tag=!dungeons:collected_winters_touch] add dungeons:collected_winters_touch
tag @a[hasitem={item=dungeons:wind_bow},tag=!dungeons:collected_wind_bow] add dungeons:collected_wind_bow
tag @a[hasitem={item=dungeons:burst_gale_bow},tag=!dungeons:collected_wind_bow] add dungeons:collected_wind_bow
tag @a[hasitem={item=dungeons:echo_of_the_valley},tag=!dungeons:collected_wind_bow] add dungeons:collected_wind_bow
tag @a[hasitem={item=dungeons:burst_gale_bow},tag=!dungeons:collected_burst_gale_bow] add dungeons:collected_burst_gale_bow
tag @a[hasitem={item=dungeons:echo_of_the_valley},tag=!dungeons:collected_echo_of_the_valley] add dungeons:collected_echo_of_the_valley
tag @a[hasitem={item=dungeons:twisting_vine_bow},tag=!dungeons:collected_twisting_vine_bow] add dungeons:collected_twisting_vine_bow
tag @a[hasitem={item=dungeons:weeping_vine_bow},tag=!dungeons:collected_twisting_vine_bow] add dungeons:collected_twisting_vine_bow
tag @a[hasitem={item=dungeons:weeping_vine_bow},tag=!dungeons:collected_weeping_vine_bow] add dungeons:collected_weeping_vine_bow
tag @a[hasitem={item=dungeons:void_bow},tag=!dungeons:collected_void_bow] add dungeons:collected_void_bow
tag @a[hasitem={item=dungeons:call_of_the_void},tag=!dungeons:collected_void_bow] add dungeons:collected_void_bow
tag @a[hasitem={item=dungeons:call_of_the_void},tag=!dungeons:collected_call_of_the_void] add dungeons:collected_call_of_the_void
tag @a[hasitem={item=minecraft:crossbow},tag=!dungeons:collected_crossbow] add dungeons:collected_crossbow
tag @a[hasitem={item=dungeons:burst_crossbow},tag=!dungeons:collected_burst_crossbow] add dungeons:collected_burst_crossbow
tag @a[hasitem={item=dungeons:corrupted_crossbow},tag=!dungeons:collected_burst_crossbow] add dungeons:collected_burst_crossbow
tag @a[hasitem={item=dungeons:soul_hunter_crossbow},tag=!dungeons:collected_burst_crossbow] add dungeons:collected_burst_crossbow
tag @a[hasitem={item=dungeons:corrupted_crossbow},tag=!dungeons:collected_corrupted_crossbow] add dungeons:collected_corrupted_crossbow
tag @a[hasitem={item=dungeons:soul_hunter_crossbow},tag=!dungeons:collected_soul_hunter_crossbow] add dungeons:collected_soul_hunter_crossbow
tag @a[hasitem={item=dungeons:exploding_crossbow},tag=!dungeons:collected_exploding_crossbow] add dungeons:collected_exploding_crossbow
tag @a[hasitem={item=dungeons:imploding_crossbow},tag=!dungeons:collected_exploding_crossbow] add dungeons:collected_exploding_crossbow
tag @a[hasitem={item=dungeons:firebolt_thrower},tag=!dungeons:collected_exploding_crossbow] add dungeons:collected_exploding_crossbow
tag @a[hasitem={item=dungeons:imploding_crossbow},tag=!dungeons:collected_imploding_crossbow] add dungeons:collected_imploding_crossbow
tag @a[hasitem={item=dungeons:firebolt_thrower},tag=!dungeons:collected_firebolt_thrower] add dungeons:collected_firebolt_thrower
tag @a[hasitem={item=dungeons:soul_crossbow},tag=!dungeons:collected_soul_crossbow] add dungeons:collected_soul_crossbow
tag @a[hasitem={item=dungeons:feral_soul_crossbow},tag=!dungeons:collected_soul_crossbow] add dungeons:collected_soul_crossbow
tag @a[hasitem={item=dungeons:voidcaller},tag=!dungeons:collected_soul_crossbow] add dungeons:collected_soul_crossbow
tag @a[hasitem={item=dungeons:feral_soul_crossbow},tag=!dungeons:collected_feral_soul_crossbow] add dungeons:collected_feral_soul_crossbow
tag @a[hasitem={item=dungeons:voidcaller},tag=!dungeons:collected_voidcaller] add dungeons:collected_voidcaller
tag @a[hasitem={item=dungeons:harpoon_crossbow},tag=!dungeons:collected_harpoon_crossbow] add dungeons:collected_harpoon_crossbow
tag @a[hasitem={item=dungeons:nautical_crossbow},tag=!dungeons:collected_harpoon_crossbow] add dungeons:collected_harpoon_crossbow
tag @a[hasitem={item=dungeons:nautical_crossbow},tag=!dungeons:collected_nautical_crossbow] add dungeons:collected_nautical_crossbow
tag @a[hasitem={item=dungeons:cog_crossbow},tag=!dungeons:collected_cog_crossbow] add dungeons:collected_cog_crossbow
tag @a[hasitem={item=dungeons:pride_of_the_piglins},tag=!dungeons:collected_cog_crossbow] add dungeons:collected_cog_crossbow
tag @a[hasitem={item=dungeons:pride_of_the_piglins},tag=!dungeons:collected_pride_of_the_piglins] add dungeons:collected_pride_of_the_piglins
tag @a[hasitem={item=dungeons:heavy_crossbow},tag=!dungeons:collected_heavy_crossbow] add dungeons:collected_heavy_crossbow
tag @a[hasitem={item=dungeons:doom_crossbow},tag=!dungeons:collected_heavy_crossbow] add dungeons:collected_heavy_crossbow
tag @a[hasitem={item=dungeons:slayer_crossbow},tag=!dungeons:collected_heavy_crossbow] add dungeons:collected_heavy_crossbow
tag @a[hasitem={item=dungeons:doom_crossbow},tag=!dungeons:collected_doom_crossbow] add dungeons:collected_doom_crossbow
tag @a[hasitem={item=dungeons:slayer_crossbow},tag=!dungeons:collected_slayer_crossbow] add dungeons:collected_slayer_crossbow
tag @a[hasitem={item=dungeons:soul_bow},tag=!dungeons:collected_soul_bow] add dungeons:collected_soul_bow
tag @a[hasitem={item=dungeons:nocturnal_bow},tag=!dungeons:collected_soul_bow] add dungeons:collected_soul_bow
tag @a[hasitem={item=dungeons:bow_of_lost_souls},tag=!dungeons:collected_soul_bow] add dungeons:collected_soul_bow
tag @a[hasitem={item=dungeons:nocturnal_bow},tag=!dungeons:collected_nocturnal_bow] add dungeons:collected_nocturnal_bow
tag @a[hasitem={item=dungeons:bow_of_lost_souls},tag=!dungeons:collected_bow_of_lost_souls] add dungeons:collected_bow_of_lost_souls
tag @a[hasitem={item=dungeons:void_bow},tag=!dungeons:collected_void_bow] add dungeons:collected_void_bow
tag @a[hasitem={item=dungeons:call_of_the_void},tag=!dungeons:collected_void_bow] add dungeons:collected_void_bow
tag @a[hasitem={item=dungeons:call_of_the_void},tag=!dungeons:collected_call_of_the_void] add dungeons:collected_call_of_the_void
tag @a[hasitem={item=dungeons:shadow_crossbow},tag=!dungeons:collected_shadow_crossbow] add dungeons:collected_shadow_crossbow
tag @a[hasitem={item=dungeons:veiled_crossbow},tag=!dungeons:collected_shadow_crossbow] add dungeons:collected_shadow_crossbow
tag @a[hasitem={item=dungeons:veiled_crossbow},tag=!dungeons:collected_veiled_crossbow] add dungeons:collected_veiled_crossbow
tag @a[hasitem={item=dungeons:haunted_bow},tag=!dungeons:collected_bow] add dungeons:collected_bow
tag @a[hasitem={item=dungeons:haunted_bow},tag=!dungeons:collected_haunted_bow] add dungeons:collected_haunted_bow
tag @a[hasitem={item=dungeons:webbed_bow},tag=!dungeons:collected_snow_touch] add dungeons:collected_snow_bow
tag @a[hasitem={item=dungeons:webbed_bow},tag=!dungeons:collected_webbed_bow] add dungeons:collected_webbed_bow
tag @a[hasitem={item=dungeons:shrieking_crossbow},tag=!dungeons:collected_shadow_crossbow] add dungeons:collected_shadow_crossbow
tag @a[hasitem={item=dungeons:shrieking_crossbow},tag=!dungeons:collected_shrieking_crossbow] add dungeons:collected_shrieking_crossbow