tag @a[hasitem={item=dungeons:sword},tag=!dungeons:collected_longsword] add dungeons:collected_longsword
tag @a[hasitem={item=dungeons:diamond_sword},tag=!dungeons:collected_longsword] add dungeons:collected_longsword
tag @a[hasitem={item=dungeons:hawkbrand},tag=!dungeons:collected_longsword] add dungeons:collected_longsword
tag @a[hasitem={item=dungeons:diamond_sword},tag=!dungeons:collected_diamond_longsword] add dungeons:collected_diamond_longsword
tag @a[hasitem={item=dungeons:hawkbrand},tag=!dungeons:collected_hawkbrand] add dungeons:collected_hawkbrand
tag @a[hasitem={item=dungeons:whip},tag=!dungeons:collected_whip] add dungeons:collected_whip
tag @a[hasitem={item=dungeons:vine_whip},tag=!dungeons:collected_whip] add dungeons:collected_whip
tag @a[hasitem={item=dungeons:vine_whip},tag=!dungeons:collected_vine_whip] add dungeons:collected_vine_whip
tag @a[hasitem={item=dungeons:katana},tag=!dungeons:collected_katana] add dungeons:collected_katana
tag @a[hasitem={item=dungeons:dark_katana},tag=!dungeons:collected_katana] add dungeons:collected_katana
tag @a[hasitem={item=dungeons:masters_katana},tag=!dungeons:collected_katana] add dungeons:collected_katana
tag @a[hasitem={item=dungeons:dark_katana},tag=!dungeons:collected_dark_katana] add dungeons:collected_dark_katana
tag @a[hasitem={item=dungeons:masters_katana},tag=!dungeons:collected_masters_katana] add dungeons:collected_masters_katana
tag @a[hasitem={item=dungeons:great_hammer},tag=!dungeons:collected_hammer] add dungeons:collected_hammer
tag @a[hasitem={item=dungeons:stormlander},tag=!dungeons:collected_hammer] add dungeons:collected_hammer
tag @a[hasitem={item=dungeons:hammer_of_gravity},tag=!dungeons:collected_hammer] add dungeons:collected_hammer
tag @a[hasitem={item=dungeons:stormlander},tag=!dungeons:collected_stormlander] add dungeons:collected_stormlander
tag @a[hasitem={item=dungeons:hammer_of_gravity},tag=!dungeons:collected_hammer_of_gravity] add dungeons:collected_hammer_of_gravity
tag @a[hasitem={item=dungeons:soul_knife},tag=!dungeons:collected_soul_knife] add dungeons:collected_soul_knife
tag @a[hasitem={item=dungeons:eternal_knife},tag=!dungeons:collected_soul_knife] add dungeons:collected_soul_knife
tag @a[hasitem={item=dungeons:truthseeker},tag=!dungeons:collected_soul_knife] add dungeons:collected_soul_knife
tag @a[hasitem={item=dungeons:eternal_knife},tag=!dungeons:collected_eternal_knife] add dungeons:collected_eternal_knife
tag @a[hasitem={item=dungeons:truthseeker},tag=!dungeons:collected_truthseeker] add dungeons:collected_truthseeker
tag @a[hasitem={item=dungeons:soul_scythe},tag=!dungeons:collected_soul_scythe] add dungeons:collected_soul_scythe
tag @a[hasitem={item=dungeons:frost_scythe},tag=!dungeons:collected_soul_scythe] add dungeons:collected_soul_scythe
tag @a[hasitem={item=dungeons:jailors_scythe},tag=!dungeons:collected_soul_scythe] add dungeons:collected_soul_scythe
tag @a[hasitem={item=dungeons:frost_scythe},tag=!dungeons:collected_frost_scythe] add dungeons:collected_frost_scythe
tag @a[hasitem={item=dungeons:jailors_scythe},tag=!dungeons:collected_jailors_scythe] add dungeons:collected_jailors_scythe
tag @a[hasitem={item=dungeons:axe},tag=!dungeons:collected_cleaving_axe] add dungeons:collected_cleaving_axe
tag @a[hasitem={item=dungeons:highlands_axe},tag=!dungeons:collected_cleaving_axe] add dungeons:collected_cleaving_axe
tag @a[hasitem={item=dungeons:firebrand},tag=!dungeons:collected_cleaving_axe] add dungeons:collected_cleaving_axe
tag @a[hasitem={item=dungeons:highlands_axe},tag=!dungeons:collected_highlands_axe] add dungeons:collected_highlands_axe
tag @a[hasitem={item=dungeons:firebrand},tag=!dungeons:collected_firebrand] add dungeons:collected_firebrand
tag @a[hasitem={item=dungeons:claymore},tag=!dungeons:collected_claymore] add dungeons:collected_claymore
tag @a[hasitem={item=dungeons:heartstealer},tag=!dungeons:collected_claymore] add dungeons:collected_claymore
tag @a[hasitem={item=dungeons:broadsword},tag=!dungeons:collected_claymore] add dungeons:collected_claymore
tag @a[hasitem={item=dungeons:great_axeblade},tag=!dungeons:collected_claymore] add dungeons:collected_claymore
tag @a[hasitem={item=dungeons:heartstealer},tag=!dungeons:collected_heartstealer] add dungeons:collected_heartstealer
tag @a[hasitem={item=dungeons:broadsword},tag=!dungeons:collected_broadsword] add dungeons:collected_broadsword
tag @a[hasitem={item=dungeons:great_axeblade},tag=!dungeons:collected_great_axeblade] add dungeons:collected_great_axeblade
tag @a[hasitem={item=dungeons:obsidian_claymore},tag=!dungeons:collected_obsidian_claymore] add dungeons:collected_obsidian_claymore
tag @a[hasitem={item=dungeons:starless_night},tag=!dungeons:collected_obsidian_claymore] add dungeons:collected_obsidian_claymore
tag @a[hasitem={item=dungeons:starless_night},tag=!dungeons:collected_starless_night] add dungeons:collected_starless_night
tag @a[hasitem={item=dungeons:rapier},tag=!dungeons:collected_rapier] add dungeons:collected_rapier
tag @a[hasitem={item=dungeons:freezing_foil},tag=!dungeons:collected_rapier] add dungeons:collected_rapier
tag @a[hasitem={item=dungeons:bee_stinger},tag=!dungeons:collected_rapier] add dungeons:collected_rapier
tag @a[hasitem={item=dungeons:freezing_foil},tag=!dungeons:collected_freezing_foil] add dungeons:collected_freezing_foil
tag @a[hasitem={item=dungeons:bee_stinger},tag=!dungeons:collected_bee_stinger] add dungeons:collected_bee_stinger
tag @a[hasitem={item=dungeons:double_axe},tag=!dungeons:collected_double_axe] add dungeons:collected_double_axe
tag @a[hasitem={item=dungeons:cursed_axe},tag=!dungeons:collected_double_axe] add dungeons:collected_double_axe
tag @a[hasitem={item=dungeons:whirlwind},tag=!dungeons:collected_double_axe] add dungeons:collected_double_axe
tag @a[hasitem={item=dungeons:cursed_axe},tag=!dungeons:collected_cursed_axe] add dungeons:collected_cursed_axe
tag @a[hasitem={item=dungeons:whirlwind},tag=!dungeons:collected_whirlwind] add dungeons:collected_whirlwind
tag @a[hasitem={item=dungeons:bone_club},tag=!dungeons:collected_bone_club] add dungeons:collected_bone_club
tag @a[hasitem={item=dungeons:bone_cudgel},tag=!dungeons:collected_bone_club] add dungeons:collected_bone_club
tag @a[hasitem={item=dungeons:bone_cudgel},tag=!dungeons:collected_bone_cudgel] add dungeons:collected_bone_cudgel
tag @a[hasitem={item=dungeons:battlestaff},tag=!dungeons:collected_battlestaff] add dungeons:collected_battlestaff
tag @a[hasitem={item=dungeons:growing_staff},tag=!dungeons:collected_battlestaff] add dungeons:collected_battlestaff
tag @a[hasitem={item=dungeons:battlestaff_of_terror},tag=!dungeons:collected_battlestaff] add dungeons:collected_battlestaff
tag @a[hasitem={item=dungeons:growing_staff},tag=!dungeons:collected_growing_staff] add dungeons:collected_growing_staff
tag @a[hasitem={item=dungeons:battlestaff_of_terror},tag=!dungeons:collected_battlestaff_of_terror] add dungeons:collected_battlestaff_of_terror
tag @a[hasitem={item=dungeons:daggers},tag=!dungeons:collected_daggers] add dungeons:collected_daggers
tag @a[hasitem={item=dungeons:sheer_daggers},tag=!dungeons:collected_daggers] add dungeons:collected_daggers
tag @a[hasitem={item=dungeons:moon_daggers},tag=!dungeons:collected_daggers] add dungeons:collected_daggers
tag @a[hasitem={item=dungeons:frost_knives},tag=!dungeons:collected_daggers] add dungeons:collected_daggers
tag @a[hasitem={item=dungeons:sheer_daggers},tag=!dungeons:collected_sheer_daggers] add dungeons:collected_sheer_daggers
tag @a[hasitem={item=dungeons:moon_daggers},tag=!dungeons:collected_moon_daggers] add dungeons:collected_moon_daggers
tag @a[hasitem={item=dungeons:frost_knives},tag=!dungeons:collected_frost_knives] add dungeons:collected_frost_knives
tag @a[hasitem={item=dungeons:cutlass},tag=!dungeons:collected_cutlass] add dungeons:collected_cutlass
tag @a[hasitem={item=dungeons:dancers_sword},tag=!dungeons:collected_cutlass] add dungeons:collected_cutlass
tag @a[hasitem={item=dungeons:nameless_blade},tag=!dungeons:collected_cutlass] add dungeons:collected_cutlass
tag @a[hasitem={item=dungeons:dancers_sword},tag=!dungeons:collected_dancers_sword] add dungeons:collected_dancers_sword
tag @a[hasitem={item=dungeons:nameless_blade},tag=!dungeons:collected_nameless_blade] add dungeons:collected_nameless_blade
tag @a[hasitem={item=dungeons:tempest_knife},tag=!dungeons:collected_tempest_knife] add dungeons:collected_tempest_knife
tag @a[hasitem={item=dungeons:resolute_tempest_knife},tag=!dungeons:collected_tempest_knife] add dungeons:collected_tempest_knife
tag @a[hasitem={item=dungeons:chill_gale_knife},tag=!dungeons:collected_tempest_knife] add dungeons:collected_tempest_knife
tag @a[hasitem={item=dungeons:resolute_tempest_knife},tag=!dungeons:collected_resolute_tempest_knife] add dungeons:collected_resolute_tempest_knife
tag @a[hasitem={item=dungeons:chill_gale_knife},tag=!dungeons:collected_chill_gale_knife] add dungeons:collected_chill_gale_knife
tag @a[hasitem={item=dungeons:anchor},tag=!dungeons:collected_anchor] add dungeons:collected_anchor
tag @a[hasitem={item=dungeons:encrusted_anchor},tag=!dungeons:collected_anchor] add dungeons:collected_anchor
tag @a[hasitem={item=dungeons:encrusted_anchor},tag=!dungeons:collected_encrusted_anchor] add dungeons:collected_encrusted_anchor
tag @a[hasitem={item=dungeons:coral_blade},tag=!dungeons:collected_coral_blade] add dungeons:collected_coral_blade
tag @a[hasitem={item=dungeons:sponge_striker},tag=!dungeons:collected_coral_blade] add dungeons:collected_coral_blade
tag @a[hasitem={item=dungeons:sponge_striker},tag=!dungeons:collected_sponge_striker] add dungeons:collected_sponge_striker
tag @a[hasitem={item=dungeons:broken_sawblade},tag=!dungeons:collected_broken_sawblade] add dungeons:collected_broken_sawblade
tag @a[hasitem={item=dungeons:mechanised_sawblade},tag=!dungeons:collected_broken_sawblade] add dungeons:collected_broken_sawblade
tag @a[hasitem={item=dungeons:mechanised_sawblade},tag=!dungeons:collected_mechanised_sawblade] add dungeons:collected_mechanised_sawblade
tag @a[hasitem={item=dungeons:gauntlets},tag=!dungeons:collected_gauntlets] add dungeons:collected_gauntlets
tag @a[hasitem={item=dungeons:maulers},tag=!dungeons:collected_gauntlets] add dungeons:collected_gauntlets
tag @a[hasitem={item=dungeons:soul_fists},tag=!dungeons:collected_gauntlets] add dungeons:collected_gauntlets
tag @a[hasitem={item=dungeons:fighters_bindings},tag=!dungeons:collected_gauntlets] add dungeons:collected_gauntlets
tag @a[hasitem={item=dungeons:maulers},tag=!dungeons:collected_maulers] add dungeons:collected_maulers
tag @a[hasitem={item=dungeons:soul_fists},tag=!dungeons:collected_soul_fists] add dungeons:collected_soul_fists
tag @a[hasitem={item=dungeons:fighters_bindings},tag=!dungeons:collected_fighters_bindings] add dungeons:collected_fighters_bindings
tag @a[hasitem={item=dungeons:glaive},tag=!dungeons:collected_glaive] add dungeons:collected_glaive
tag @a[hasitem={item=dungeons:venom_glaive},tag=!dungeons:collected_glaive] add dungeons:collected_glaive
tag @a[hasitem={item=dungeons:grave_bane},tag=!dungeons:collected_glaive] add dungeons:collected_glaive
tag @a[hasitem={item=dungeons:venom_glaive},tag=!dungeons:collected_venom_glaive] add dungeons:collected_venom_glaive
tag @a[hasitem={item=dungeons:grave_bane},tag=!dungeons:collected_grave_bane] add dungeons:collected_grave_bane
tag @a[hasitem={item=dungeons:backstabber},tag=!dungeons:collected_backstabber] add dungeons:collected_backstabber
tag @a[hasitem={item=dungeons:swift_striker},tag=!dungeons:collected_backstabber] add dungeons:collected_backstabber
tag @a[hasitem={item=dungeons:swift_striker},tag=!dungeons:collected_swift_striker] add dungeons:collected_swift_striker
tag @a[hasitem={item=dungeons:void_touched_blades},tag=!dungeons:collected_void_touched_blades] add dungeons:collected_void_touched_blades
tag @a[hasitem={item=dungeons:the_beginning_and_the_end},tag=!dungeons:collected_void_touched_blades] add dungeons:collected_void_touched_blades
tag @a[hasitem={item=dungeons:the_beginning_and_the_end},tag=!dungeons:collected_the_beginning_and_the_end] add dungeons:collected_the_beginning_and_the_end
tag @a[hasitem={item=dungeons:sinister_sword},tag=!dungeons:collected_longsword] add dungeons:collected_longsword
tag @a[hasitem={item=dungeons:sinister_sword},tag=!dungeons:collected_sinister_sword] add dungeons:collected_sinister_sword
tag @a[hasitem={item=dungeons:bonehead_hammer},tag=!dungeons:collected_hammer] add dungeons:collected_hammer
tag @a[hasitem={item=dungeons:bonehead_hammer},tag=!dungeons:collected_bonehead_hammer] add dungeons:collected_bonehead_hammer
tag @a[hasitem={item=dungeons:skull_scythe},tag=!dungeons:collected_soul_scythe] add dungeons:collected_soul_scythe
tag @a[hasitem={item=dungeons:skull_scythe},tag=!dungeons:collected_skull_scythe] add dungeons:collected_skull_scythe
tag @a[hasitem={item=dungeons:cackling_broom},tag=!dungeons:collected_glaive] add dungeons:collected_glaive
tag @a[hasitem={item=dungeons:cackling_broom},tag=!dungeons:collected_cackling_broom] add dungeons:collected_cackling_broom