tag @a[hasitem={item=dungeons:blast_fungus},tag=!dungeons:collected_blast_fungus] add dungeons:collected_blast_fungus
tag @a[hasitem={item=dungeons:rare_blast_fungus},tag=!dungeons:collected_blast_fungus] add dungeons:collected_blast_fungus
tag @a[hasitem={item=dungeons:boots_of_swiftness},tag=!dungeons:collected_boots_of_swiftness] add dungeons:collected_boots_of_swiftness
tag @a[hasitem={item=dungeons:rare_boots_of_swiftness},tag=!dungeons:collected_boots_of_swiftness] add dungeons:collected_boots_of_swiftness
tag @a[hasitem={item=dungeons:buzzy_nest},tag=!dungeons:collected_buzzy_nest] add dungeons:collected_buzzy_nest
tag @a[hasitem={item=dungeons:rare_buzzy_nest},tag=!dungeons:collected_buzzy_nest] add dungeons:collected_buzzy_nest
tag @a[hasitem={item=dungeons:corrupted_beacon},tag=!dungeons:collected_corrupted_beacon] add dungeons:collected_corrupted_beacon
tag @a[hasitem={item=dungeons:rare_corrupted_beacon},tag=!dungeons:collected_corrupted_beacon] add dungeons:collected_corrupted_beacon
tag @a[hasitem={item=dungeons:corrupted_seeds},tag=!dungeons:collected_corrupted_seeds] add dungeons:collected_corrupted_seeds
tag @a[hasitem={item=dungeons:rare_corrupted_seeds},tag=!dungeons:collected_corrupted_seeds] add dungeons:collected_corrupted_seeds
tag @a[hasitem={item=dungeons:death_cap_mushroom},tag=!dungeons:collected_death_cap_mushroom] add dungeons:collected_death_cap_mushroom
tag @a[hasitem={item=dungeons:rare_death_cap_mushroom},tag=!dungeons:collected_death_cap_mushroom] add dungeons:collected_death_cap_mushroom
tag @a[hasitem={item=dungeons:enchanted_grass},tag=!dungeons:collected_enchanted_grass] add dungeons:collected_enchanted_grass
tag @a[hasitem={item=dungeons:rare_enchanted_grass},tag=!dungeons:collected_enchanted_grass] add dungeons:collected_enchanted_grass
tag @a[hasitem={item=dungeons:enchanters_tome},tag=!dungeons:collected_enchanters_tome] add dungeons:collected_enchanters_tome
tag @a[hasitem={item=dungeons:rare_enchanters_tome},tag=!dungeons:collected_enchanters_tome] add dungeons:collected_enchanters_tome
tag @a[hasitem={item=dungeons:eye_of_the_guardian},tag=!dungeons:collected_eye_of_the_guardian] add dungeons:collected_eye_of_the_guardian
tag @a[hasitem={item=dungeons:rare_eye_of_the_guardian},tag=!dungeons:collected_eye_of_the_guardian] add dungeons:collected_eye_of_the_guardian
tag @a[hasitem={item=dungeons:ghost_cloak},tag=!dungeons:collected_ghost_cloak] add dungeons:collected_ghost_cloak
tag @a[hasitem={item=dungeons:rare_ghost_cloak},tag=!dungeons:collected_ghost_cloak] add dungeons:collected_ghost_cloak
tag @a[hasitem={item=dungeons:golem_kit},tag=!dungeons:collected_golem_kit] add dungeons:collected_golem_kit
tag @a[hasitem={item=dungeons:rare_golem_kit},tag=!dungeons:collected_golem_kit] add dungeons:collected_golem_kit
tag @a[hasitem={item=dungeons:gong_of_weakening},tag=!dungeons:collected_gong_of_weakening] add dungeons:collected_gong_of_weakening
tag @a[hasitem={item=dungeons:rare_gong_of_weakening},tag=!dungeons:collected_gong_of_weakening] add dungeons:collected_gong_of_weakening
tag @a[hasitem={item=dungeons:harvester},tag=!dungeons:collected_harvester] add dungeons:collected_harvester
tag @a[hasitem={item=dungeons:rare_harvester},tag=!dungeons:collected_harvester] add dungeons:collected_harvester
tag @a[hasitem={item=dungeons:ice_wand},tag=!dungeons:collected_ice_wand] add dungeons:collected_ice_wand
tag @a[hasitem={item=dungeons:rare_ice_wand},tag=!dungeons:collected_ice_wand] add dungeons:collected_ice_wand
tag @a[hasitem={item=dungeons:iron_hide_amulet},tag=!dungeons:collected_iron_hide_amulet] add dungeons:collected_iron_hide_amulet
tag @a[hasitem={item=dungeons:rare_iron_hide_amulet},tag=!dungeons:collected_iron_hide_amulet] add dungeons:collected_iron_hide_amulet
tag @a[hasitem={item=dungeons:light_feather},tag=!dungeons:collected_light_feather] add dungeons:collected_light_feather
tag @a[hasitem={item=dungeons:rare_light_feather},tag=!dungeons:collected_light_feather] add dungeons:collected_light_feather
tag @a[hasitem={item=dungeons:lightning_rod},tag=!dungeons:collected_lightning_rod] add dungeons:collected_lightning_rod
tag @a[hasitem={item=dungeons:rare_lightning_rod},tag=!dungeons:collected_lightning_rod] add dungeons:collected_lightning_rod
tag @a[hasitem={item=dungeons:powershaker},tag=!dungeons:collected_powershaker] add dungeons:collected_powershaker
tag @a[hasitem={item=dungeons:rare_powershaker},tag=!dungeons:collected_powershaker] add dungeons:collected_powershaker
tag @a[hasitem={item=dungeons:satchel_of_elements},tag=!dungeons:collected_satchel_of_elements] add dungeons:collected_satchel_of_elements
tag @a[hasitem={item=dungeons:rare_satchel_of_elements},tag=!dungeons:collected_satchel_of_elements] add dungeons:collected_satchel_of_elements
tag @a[hasitem={item=dungeons:satchel_of_elixirs},tag=!dungeons:collected_satchel_of_elixirs] add dungeons:collected_satchel_of_elixirs
tag @a[hasitem={item=dungeons:rare_satchel_of_elixirs},tag=!dungeons:collected_satchel_of_elixirs] add dungeons:collected_satchel_of_elixirs
tag @a[hasitem={item=dungeons:satchel_of_snacks},tag=!dungeons:collected_satchel_of_snacks] add dungeons:collected_satchel_of_snacks
tag @a[hasitem={item=dungeons:rare_satchel_of_snacks},tag=!dungeons:collected_satchel_of_snacks] add dungeons:collected_satchel_of_snacks
tag @a[hasitem={item=dungeons:scatter_mines},tag=!dungeons:collected_scatter_mines] add dungeons:collected_scatter_mines
tag @a[hasitem={item=dungeons:rare_scatter_mines},tag=!dungeons:collected_scatter_mines] add dungeons:collected_scatter_mines
tag @a[hasitem={item=dungeons:shadow_shifter},tag=!dungeons:collected_shadow_shifter] add dungeons:collected_shadow_shifter
tag @a[hasitem={item=dungeons:rare_shadow_shifter},tag=!dungeons:collected_shadow_shifter] add dungeons:collected_shadow_shifter
tag @a[hasitem={item=dungeons:shock_powder},tag=!dungeons:collected_shock_powder] add dungeons:collected_shock_powder
tag @a[hasitem={item=dungeons:rare_shock_powder},tag=!dungeons:collected_shock_powder] add dungeons:collected_shock_powder
tag @a[hasitem={item=dungeons:soul_healer},tag=!dungeons:collected_soul_healer] add dungeons:collected_soul_healer
tag @a[hasitem={item=dungeons:rare_soul_healer},tag=!dungeons:collected_soul_healer] add dungeons:collected_soul_healer
tag @a[hasitem={item=dungeons:soul_lantern},tag=!dungeons:collected_soul_lantern] add dungeons:collected_soul_lantern
tag @a[hasitem={item=dungeons:rare_soul_lantern},tag=!dungeons:collected_soul_lantern] add dungeons:collected_soul_lantern
tag @a[hasitem={item=dungeons:spinblade},tag=!dungeons:collected_spinblade] add dungeons:collected_spinblade
tag @a[hasitem={item=dungeons:rare_spinblade},tag=!dungeons:collected_spinblade] add dungeons:collected_spinblade
tag @a[hasitem={item=dungeons:tome_of_duplication},tag=!dungeons:collected_tome_of_duplication] add dungeons:collected_tome_of_duplication
tag @a[hasitem={item=dungeons:rare_tome_of_duplication},tag=!dungeons:collected_tome_of_duplication] add dungeons:collected_tome_of_duplication
tag @a[hasitem={item=dungeons:totem_of_casting},tag=!dungeons:collected_totem_of_casting] add dungeons:collected_totem_of_casting
tag @a[hasitem={item=dungeons:rare_totem_of_casting},tag=!dungeons:collected_totem_of_casting] add dungeons:collected_totem_of_casting
tag @a[hasitem={item=dungeons:totem_of_regeneration},tag=!dungeons:collected_totem_of_regeneration] add dungeons:collected_totem_of_regeneration
tag @a[hasitem={item=dungeons:rare_totem_of_regeneration},tag=!dungeons:collected_totem_of_regeneration] add dungeons:collected_totem_of_regeneration
tag @a[hasitem={item=dungeons:totem_of_shielding},tag=!dungeons:collected_totem_of_shielding] add dungeons:collected_totem_of_shielding
tag @a[hasitem={item=dungeons:rare_totem_of_shielding},tag=!dungeons:collected_totem_of_shielding] add dungeons:collected_totem_of_shielding
tag @a[hasitem={item=dungeons:updraft_tome},tag=!dungeons:collected_updraft_tome] add dungeons:collected_updraft_tome
tag @a[hasitem={item=dungeons:rare_updraft_tome},tag=!dungeons:collected_updraft_tome] add dungeons:collected_updraft_tome
tag @a[hasitem={item=dungeons:vexing_chant},tag=!dungeons:collected_vexing_chant] add dungeons:collected_vexing_chant
tag @a[hasitem={item=dungeons:rare_vexing_chant},tag=!dungeons:collected_vexing_chant] add dungeons:collected_vexing_chant
tag @a[hasitem={item=dungeons:wind_horn},tag=!dungeons:collected_wind_horn] add dungeons:collected_wind_horn
tag @a[hasitem={item=dungeons:rare_wind_horn},tag=!dungeons:collected_wind_horn] add dungeons:collected_wind_horn
tag @a[hasitem={item=dungeons:corrupted_pumpkin},tag=!dungeons:collected_corrupted_beacon] add dungeons:collected_corrupted_beacon
tag @a[hasitem={item=dungeons:corrupted_pumpkin},tag=!dungeons:collected_corrupted_pumpkin] add dungeons:collected_corrupted_pumpkin