summon dungeons:wretched_wraith_fire ~-2~~5
summon dungeons:wretched_wraith_fire ~-1~~5
summon dungeons:wretched_wraith_fire ~~~5
summon dungeons:wretched_wraith_fire ~1~~5
summon dungeons:wretched_wraith_fire ~2~~5
summon dungeons:wretched_wraith_fire ~-3~~4
summon dungeons:wretched_wraith_fire ~3~~4
summon dungeons:wretched_wraith_fire ~-4~~3
summon dungeons:wretched_wraith_fire ~4~~3
summon dungeons:wretched_wraith_fire ~5~~-2
summon dungeons:wretched_wraith_fire ~5~~-1
summon dungeons:wretched_wraith_fire ~5~~0
summon dungeons:wretched_wraith_fire ~5~~1
summon dungeons:wretched_wraith_fire ~5~~2
summon dungeons:wretched_wraith_fire ~-5~~-2
summon dungeons:wretched_wraith_fire ~-5~~-1
summon dungeons:wretched_wraith_fire ~-5~~0
summon dungeons:wretched_wraith_fire ~-5~~1
summon dungeons:wretched_wraith_fire ~-5~~2
summon dungeons:wretched_wraith_fire ~-4~~-3
summon dungeons:wretched_wraith_fire ~4~~-3
summon dungeons:wretched_wraith_fire ~-3~~-4
summon dungeons:wretched_wraith_fire ~3~~-4
summon dungeons:wretched_wraith_fire ~-2~~-5
summon dungeons:wretched_wraith_fire ~-1~~-5
summon dungeons:wretched_wraith_fire ~~~-5
summon dungeons:wretched_wraith_fire ~1~~-5
summon dungeons:wretched_wraith_fire ~2~~-5